import type { CSSProperties } from "react";

/** Co-located styles for ProjectContextView and its sub-components. */
export const s = {
  page: { display: "flex", height: "calc(100vh - 52px)" } satisfies CSSProperties,
  left: {
    width: 320,
    flexShrink: 0,
    borderRight: "1px solid var(--border)",
    display: "flex",
    flexDirection: "column",
    background: "var(--bg-surface)",
  } satisfies CSSProperties,
  leftHead: { padding: "16px 16px 8px" } satisfies CSSProperties,
  h1: { fontSize: 18, fontWeight: 700 } satisfies CSSProperties,
  rootPath: { fontSize: 12, color: "var(--text-muted)", marginTop: 2 } satisfies CSSProperties,
  toolbar: { display: "flex", flexWrap: "wrap", gap: 6, padding: "4px 16px 8px" } satisfies CSSProperties,
  visuallyHidden: {
    position: "absolute",
    width: 1,
    height: 1,
    margin: -1,
    padding: 0,
    overflow: "hidden",
    clip: "rect(0 0 0 0)",
    whiteSpace: "nowrap",
    border: 0,
  } satisfies CSSProperties,
  note: { fontSize: 12, color: "var(--text-muted)", padding: "0 16px 8px" } satisfies CSSProperties,
  list: { flex: 1, overflow: "auto", padding: "0 8px" } satisfies CSSProperties,
  item: (active: boolean): CSSProperties => ({
    display: "flex",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 8,
    width: "100%",
    textAlign: "left",
    padding: "7px 8px",
    borderRadius: 6,
    border: "none",
    cursor: "pointer",
    background: active ? "var(--bg-hover)" : "transparent",
    color: "var(--text-primary)",
  }),
  itemPath: { fontSize: 12, flex: 1, minWidth: 0, wordBreak: "break-all" } satisfies CSSProperties,
  kind: { textTransform: "capitalize" } satisfies CSSProperties,
  count: { fontSize: 12, color: "var(--text-muted)", padding: "10px 16px", borderTop: "1px solid var(--border)" } satisfies CSSProperties,
  right: { flex: 1, minWidth: 0, overflow: "auto", padding: "20px 28px" } satisfies CSSProperties,
  rightHead: { display: "flex", alignItems: "center", flexWrap: "wrap", gap: 12, marginBottom: 14 } satisfies CSSProperties,
  path: { fontSize: 16, fontWeight: 700, wordBreak: "break-all" } satisfies CSSProperties,
  prompt: { fontSize: 13, color: "var(--text-muted)" } satisfies CSSProperties,
  spacer: { flex: 1 } satisfies CSSProperties,
  modeGroup: { display: "inline-flex", gap: 4 } satisfies CSSProperties,
  modeBtn: (pressed: boolean): CSSProperties => ({
    padding: "5px 12px",
    fontSize: 12.5,
    fontWeight: 500,
    borderRadius: 6,
    border: "1px solid var(--border-strong)",
    cursor: "pointer",
    background: pressed ? "var(--bg-hover)" : "transparent",
    color: pressed ? "var(--text-primary)" : "var(--text-secondary)",
  }),
  status: { fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
  statusDirty: { fontSize: 12, color: "var(--warn, var(--text-primary))", fontWeight: 600 } satisfies CSSProperties,
  readOnlyNote: { display: "flex", alignItems: "center", gap: 10, fontSize: 13, color: "var(--text-secondary)", marginBottom: 14 } satisfies CSSProperties,
  banner: {
    display: "flex",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 10,
    padding: "10px 12px",
    marginBottom: 14,
    borderRadius: 7,
    border: "1px solid var(--crit)",
    background: "var(--crit-bg)",
    fontSize: 13,
  } satisfies CSSProperties,
  bannerText: { flex: 1, minWidth: 200 } satisfies CSSProperties,
  editor: {
    width: "100%",
    minHeight: 420,
    resize: "vertical",
    padding: "10px 12px",
    borderRadius: 7,
    border: "1px solid var(--border-strong)",
    background: "var(--bg-elevated)",
    color: "var(--text-primary)",
    fontSize: 13,
    lineHeight: 1.55,
    outline: "none",
  } satisfies CSSProperties,
  dialogBody: { padding: "18px 24px", display: "flex", flexDirection: "column", gap: 8 } satisfies CSSProperties,
  dialogLabel: { fontSize: 13, fontWeight: 500 } satisfies CSSProperties,
  dialogError: { fontSize: 13, color: "var(--crit)" } satisfies CSSProperties,
  dialogFooter: { display: "flex", justifyContent: "flex-end", gap: 8 } satisfies CSSProperties,
} as const;
